name: test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java-version: [24, 21, 17, 11]

    steps:
    - uses: actions/checkout@v5
    - name: Set up Java ${{ matrix.java-version }}
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java-version }}
    - name: Build and test
      run: ./mvnw -B -T 1C clean test --file pom.xml
