name: test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Java 18
      uses: actions/setup-java@v1
      with:
        java-version: 18
    - name: Build with Java 18
      run: ./mvnw -B clean test --file pom.xml 		
    - name: Set up Java 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Build with Java 17
      run: ./mvnw -B clean test --file pom.xml        
    - name: Set up Java 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Java 11
      run: ./mvnw -B clean test --file pom.xml    
    - name: Deploy to Sonatype
      run: ./mvnw -B -Drepo.username=${{secrets.SONATYPE_USERNAME}} -Drepo.password=${{secrets.SONATYPE_PASSWORD}} clean deploy -DskipTests=true --settings mySettings.xml
